VERSION 0.8

IMPORT ../ AS examples

common:
    ARG --required python_version
    FROM examples+common-base --python_version=$python_version
 
    RUN . /xronos/.venv/bin/activate && pip install --no-index --find-links=wheels xronos

    WORKDIR /xronos/examples/style-guide
    COPY *.py .
    COPY --dir test .

test:
    ARG --required python_version
    FROM +common --python_version=$python_version
    WORKDIR /xronos/examples/style-guide
    RUN . /xronos/.venv/bin/activate && pytest --config-file=../pytest.ini

lint:
    FROM +common --python_version=3.12
    WORKDIR /xronos/examples/style-guide
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml check
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml format --diff
    RUN . /xronos/.venv/bin/activate && mypy --config-file=../mypy.ini .
    RUN . /xronos/.venv/bin/activate && pyright --project .. .
