VERSION 0.8

IMPORT ../ AS examples

common:
    FROM --pass-args examples+common-base
 
    RUN . /xronos/.venv/bin/activate && pip install --no-index --find-links=wheels xronos

    WORKDIR /xronos/examples/style-guide
    COPY *.py .
    COPY --dir test .

test:
    FROM --pass-args +common
    WORKDIR /xronos/examples/style-guide
    RUN . /xronos/.venv/bin/activate && pytest --config-file=../pytest.ini

lint:
    FROM +common
    WORKDIR /xronos/examples/style-guide
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml check
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml format --diff
    RUN . /xronos/.venv/bin/activate && mypy --config-file=../mypy.ini .
    RUN . /xronos/.venv/bin/activate && pyright --project .. .
