# SPDX-FileCopyrightText: (c) 2025 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause

VERSION 0.8

IMPORT ../ AS examples
IMPORT ../../base-images AS base-images

dependencies:
    # download wheels for all requirements except xronos
    ARG --required python_version
    FROM base-images+python-venv --python_version=$python_version
    ENV DEBIAN_FRONTEND=noninteractive
    ENV DISPLAY=localhost:0.0

    # debian dependencies
    RUN apt-get install -y -qq --no-install-recommends libportaudio2

    # python dependencies
    COPY requirements.txt ./
    RUN sed -i /^xronos/d requirements.txt
    RUN . /xronos/.venv/bin/activate && pip wheel -r requirements.txt --wheel-dir=wheels
    SAVE ARTIFACT wheels /wheels

common:
    ARG --required python_version
    FROM examples+common-base --python_version=$python_version
    COPY (+dependencies/wheels --python_version=$python_version) wheels
    COPY requirements.txt .
    RUN . /xronos/.venv/bin/activate && pip install --no-index --find-links=wheels -r requirements.txt
 
    WORKDIR /xronos/examples/keyboard-synth
    COPY *.py .
    COPY static .

lint:
    FROM +common --python_version=3.12
    WORKDIR /xronos/examples/keyboard-synth
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml check
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml format --diff
    RUN . /xronos/.venv/bin/activate && mypy --config-file=../mypy.ini .
    RUN . /xronos/.venv/bin/activate && pyright --project .. .