VERSION 0.8

IMPORT ../ AS examples
IMPORT ../../base-images AS base-images

dependencies:
    # download wheels for all requirements except xronos
    ARG --required python_version
    FROM base-images+python-venv --python_version=$python_version
    COPY requirements.txt ./
    RUN sed -i /^xronos/d requirements.txt
    RUN . /xronos/.venv/bin/activate && pip wheel -r requirements.txt --wheel-dir=wheels
    SAVE ARTIFACT wheels /wheels

common:
    ARG --required python_version
    FROM examples+common-base --python_version=$python_version
    COPY (+dependencies/wheels --python_version=$python_version) wheels
    COPY requirements.txt .
    RUN . /xronos/.venv/bin/activate && pip install --no-index --find-links=wheels -r requirements.txt
 
    WORKDIR /xronos/examples/webots
    COPY --dir controllers .

lint:
    FROM +common --python_version=3.12
    WORKDIR /xronos/examples/webots
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml check
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml format --diff
    RUN . /xronos/.venv/bin/activate && mypy --config-file=../mypy.ini .
    RUN . /xronos/.venv/bin/activate && pyright --project .. .