VERSION 0.8

IMPORT ../base-images AS base-images
IMPORT ../xronos AS xronos

test:
    BUILD +test-examples --python_version=3.10 --python_version=3.11 --python_version=3.12 --python_version=3.13
    BUILD ./YOLO+test --python_version=3.12

test-examples:
    ARG --required python_version
    BUILD ./montecarlo+test --python_version=$python_version
    BUILD ./style-guide+test --python_version=$python_version

lint:
    BUILD ./montecarlo+lint
    BUILD ./robot-arm+lint
    BUILD ./simple-neural-net+lint
    BUILD ./style-guide+lint
    BUILD ./YOLO+lint
    BUILD ./keyboard-synth+lint

copy:
    # Copies the examples directory to the root of the image and exports it as an artifact.
    # This is used in the docs build to get access to the examples.
    FROM base-images+common-base
    COPY --dir . ./examples
    SAVE ARTIFACT examples

configs:
    FROM base-images+common-base
    WORKDIR /xronos/examples
    COPY mypy.ini ruff.toml pyrightconfig.json pytest.ini .
    WORKDIR /xronos
    SAVE ARTIFACT examples

common-base:
    ARG --required python_version
    FROM base-images+python-venv --python_version=$python_version
    WORKDIR /xronos
    RUN mkdir wheels
    COPY (xronos+wheel/xronos-*.whl  --python_version=$python_version) ./wheels
    COPY +configs/examples examples
