VERSION 0.8

IMPORT ../ AS examples
IMPORT ../../xronos-telemetry AS xronos-telemetry

common:
    FROM --pass-args examples+common-base

    COPY --pass-args xronos-telemetry+wheel/xronos_telemetry-*.whl .
    RUN . /xronos/.venv/bin/activate && pip install xronos_telemetry-*.whl

    COPY requirements.txt .
    RUN . /xronos/.venv/bin/activate && pip install -r requirements.txt
 
    WORKDIR /xronos/examples/montecarlo
    COPY *.py .
    COPY --dir test .

lint:
    ARG python_version
    FROM --pass-args +common
    WORKDIR /xronos/examples/montecarlo
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml check
    RUN . /xronos/.venv/bin/activate && ruff --config=../ruff.toml format --diff
    RUN . /xronos/.venv/bin/activate && mypy --config-file=../mypy.ini .
    RUN . /xronos/.venv/bin/activate && pyright --project .. .

test:
    ARG python_version
    FROM --pass-args +common
    WORKDIR /xronos/examples/montecarlo
    RUN . /xronos/.venv/bin/activate && pytest --config-file=../pytest.ini